OLED_ENABLE = yes
OLED_DRIVER = SSD1306      # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGB_MATRIX_ENABLE = no     # Disable keyboard RGB matrix, as it is enabled by default on rev3
# RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
# CONVERT_TO=promicro_rp2040 # Liatris chip
RGBLIGHT_ENABLE = yes # Enables QMK's RGB code
WS2812_DRIVER = vendor # Use the RP2040's PIO interface
MOUSEKEY_ENABLE = yes
RAW_ENABLE = yes
